name: tictacthrow
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # google_sign_in: ^3.0.4
  # flutter_facebook_login: ^1.1.1
  sensors: ^0.3.4
  web3dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/facebook.png
